export interface FDRate {
  id: string;
  bankName: string;
  bankNameHi: string;
  bankCode: string;
  bankType: "public" | "private" | "small-finance";
  bookingUrl: string;
  regularRate: number;
  seniorRate: number;
  minAmount: number;
  maxAmount: number;
  tenorMinMonths: number;
  tenorMaxMonths: number;
  tenorLabel: string;
  compounding: "quarterly" | "monthly" | "annual";
  dicgcInsured: boolean;
  badge?: "best-value" | "popular" | "safe-choice";
  color: string;
}

export const FD_RATES: FDRate[] = [
  {
    id: "au-sfb",
    bankName: "AU Small Finance Bank",
    bankNameHi: "एयू स्मॉल फाइनेंस",
    bankCode: "AU",
    bankType: "small-finance",
    bookingUrl: "https://www.aubank.in/personal-banking/deposits/fixed-deposit",
    regularRate: 8.0,
    seniorRate: 8.5,
    minAmount: 5000,
    maxAmount: 10000000,
    tenorMinMonths: 12,
    tenorMaxMonths: 36,
    tenorLabel: "1 - 3 Years",
    compounding: "quarterly",
    dicgcInsured: true,
    badge: "best-value",
    color: "#6B21A8",
  },
  {
    id: "hdfc",
    bankName: "HDFC Bank",
    bankNameHi: "एचडीएफसी बैंक",
    bankCode: "HDFC",
    bankType: "private",
    bookingUrl: "https://www.hdfcbank.com/personal/save/deposits/fixed-deposit",
    regularRate: 7.75,
    seniorRate: 8.25,
    minAmount: 5000,
    maxAmount: 100000000,
    tenorMinMonths: 12,
    tenorMaxMonths: 120,
    tenorLabel: "400 Days",
    compounding: "quarterly",
    dicgcInsured: true,
    badge: "popular",
    color: "#004C8F",
  },
  {
    id: "sbi",
    bankName: "State Bank of India",
    bankNameHi: "भारतीय स्टेट बैंक",
    bankCode: "SBI",
    bankType: "public",
    bookingUrl: "https://sbi.co.in/web/personal-banking/investments-deposits/deposits/tax-saving-scheme",
    regularRate: 7.5,
    seniorRate: 8.0,
    minAmount: 1000,
    maxAmount: 100000000,
    tenorMinMonths: 12,
    tenorMaxMonths: 120,
    tenorLabel: "1 - 2 Years",
    compounding: "quarterly",
    dicgcInsured: true,
    badge: "safe-choice",
    color: "#22409A",
  },
  {
    id: "kotak",
    bankName: "Kotak Mahindra Bank",
    bankNameHi: "कोटक महिंद्रा बैंक",
    bankCode: "KOTAK",
    bankType: "private",
    bookingUrl: "https://www.kotak.com/en/personal-banking/deposits/fixed-deposit.html",
    regularRate: 7.25,
    seniorRate: 7.75,
    minAmount: 5000,
    maxAmount: 100000000,
    tenorMinMonths: 7,
    tenorMaxMonths: 120,
    tenorLabel: "1 - 5 Years",
    compounding: "quarterly",
    dicgcInsured: true,
    color: "#E3000F",
  },
  {
    id: "icici",
    bankName: "ICICI Bank",
    bankNameHi: "आईसीआईसीआई बैंक",
    bankCode: "ICICI",
    bankType: "private",
    bookingUrl: "https://www.icicibank.com/personal-banking/deposits/fixed-deposit",
    regularRate: 7.2,
    seniorRate: 7.7,
    minAmount: 10000,
    maxAmount: 100000000,
    tenorMinMonths: 12,
    tenorMaxMonths: 120,
    tenorLabel: "1 - 10 Years",
    compounding: "quarterly",
    dicgcInsured: true,
    color: "#F58220",
  },
  {
    id: "axis",
    bankName: "Axis Bank",
    bankNameHi: "एक्सिस बैंक",
    bankCode: "AXIS",
    bankType: "private",
    bookingUrl: "https://www.axisbank.com/retail/deposits/fixed-deposits",
    regularRate: 7.15,
    seniorRate: 7.65,
    minAmount: 5000,
    maxAmount: 100000000,
    tenorMinMonths: 12,
    tenorMaxMonths: 120,
    tenorLabel: "1 - 10 Years",
    compounding: "quarterly",
    dicgcInsured: true,
    badge: "popular",
    color: "#97144D",
  },
  {
    id: "pnb",
    bankName: "Punjab National Bank",
    bankNameHi: "पंजाब नेशनल बैंक",
    bankCode: "PNB",
    bankType: "public",
    bookingUrl: "https://www.pnbindia.in/fixed-deposit.html",
    regularRate: 7.25,
    seniorRate: 7.75,
    minAmount: 1000,
    maxAmount: 100000000,
    tenorMinMonths: 12,
    tenorMaxMonths: 120,
    tenorLabel: "2 - 3 Years",
    compounding: "quarterly",
    dicgcInsured: true,
    color: "#1A237E",
  },
  {
    id: "bob",
    bankName: "Bank of Baroda",
    bankNameHi: "बैंक ऑफ बड़ौदा",
    bankCode: "BOB",
    bankType: "public",
    bookingUrl: "https://www.bankofbaroda.in/personal-banking/accounts/fixed-deposit",
    regularRate: 7.15,
    seniorRate: 7.65,
    minAmount: 1000,
    maxAmount: 100000000,
    tenorMinMonths: 12,
    tenorMaxMonths: 120,
    tenorLabel: "1 - 3 Years",
    compounding: "quarterly",
    dicgcInsured: true,
    color: "#F26522",
  },
];
